name: Create Archive
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository code
      uses: actions/checkout@v3
      run: rm -rf .github
    - name: Zipping
      run: zip CDLine-${{github.ref_name}}.zip Core.lua MainFrame.xml LICENSE README.md CDLine.toc
    - name: Create Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        token: ${{ secrets.GITHUB_TOKEN }}
      run: hub release create -a "CDLine-${{github.ref_name}}" -m "CDLine ${{github.ref_name}}" "${{github.ref_name}}"